// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfbfomeejjmcvzxmbgku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mYmZvbWVlamptY3Z6eG1iZ2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTA4MTQsImV4cCI6MjA2MjI4NjgxNH0.1CBPEbqnyXCZogm92hAYUP5Oh6MdI3-qjXb2j1UXn5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);